# Generated by Django 2.2 on 2020-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat_app', '0002_auto_20200818_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='disp',
            field=models.FloatField(verbose_name=(0, 1, 2, 3, 4, 5)),
        ),
    ]
